MCR_REGISTER_COMPSID( GOC_Type_Hero )
MCR_REGISTER_COMPSID( GOC_Type_Floor )
MCR_REGISTER_COMPSID( GOC_Type_Floor1 )
MCR_REGISTER_COMPSID( GOC_Type_Button1 )
MCR_REGISTER_COMPSID( GOC_Type_Door1 )
MCR_REGISTER_COMPSID( GOC_Type_Wall )
MCR_REGISTER_COMPSID( GOC_Type_Wall_Selectable )
MCR_REGISTER_COMPSID( GOC_Type_NOTHING )//for objects like the arrows etc
MCR_REGISTER_COMPSID( GOC_Type_CUBE_THROWER )

//temp remove once gameplay start
MCR_REGISTER_COMPSID( GOC_Type_CUBE )
MCR_REGISTER_COMPSID( GOC_Type_NONROTATINGCUBE )
MCR_REGISTER_COMPSID( GOC_Type_SPHERE )
MCR_REGISTER_COMPSID( GOC_Type_QUAD )

MCR_REGISTER_COMPSID( GOC_Type_EXPLICIT )
MCR_REGISTER_COMPSID( GOC_Type_MIDPOINT )
MCR_REGISTER_COMPSID( GOC_Type_RK4 )
MCR_REGISTER_COMPSID( GOC_Type_SEMIIMPLICIT )
MCR_REGISTER_COMPSID( GOC_Type_VERLET )




